[package]
edition = "2021"
name = "ytmusic-gui"
version = "0.1.0"
authors = ["Tyman"]

[workspace]

[dependencies]
iced = { version = "0.3", features = ["tokio"] }
reqwest = { version = "0.11.10", features = ["gzip"] }
ytmusic-api = { path = "ytmusic-api" }
tempfile = "3.3.0"
