[package]
edition = "2021"
name = "ytmusic-gui"
version = "0.1.0"
authors = ["Tyman"]

[workspace]

[dependencies]
iced = "0.3"
reqwest = { version = "0.11.10", features = ["gzip"] }
ytmusic-api = { path = "ytmusic-api" }
